/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'center' : IDL.Null,
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'vendor' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'kyc_doc' : IDL.Opt(ExternalBlob),
  'principal' : IDL.Principal,
  'gst_number' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'bank_kyc' : IDL.Opt(IDL.Text),
  'kyc_status' : IDL.Bool,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'kyc_doc' : IDL.Opt(ExternalBlob),
  'gst_number' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'bank_kyc' : IDL.Opt(IDL.Text),
  'kyc_status' : IDL.Bool,
  'phone' : IDL.Text,
});
export const ProductStatus = IDL.Variant({
  'rented' : IDL.Null,
  'atVendor' : IDL.Null,
  'onTrial' : IDL.Null,
  'underSanitization' : IDL.Null,
  'atCenter' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'deposit_amount' : IDL.Nat,
  'availability_status' : ProductStatus,
  'rental_price' : IDL.Nat,
  'description' : IDL.Text,
  'sanitization_status' : IDL.Bool,
  'approved' : IDL.Bool,
  'center_id' : IDL.Nat,
  'vendor_id' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const ProductQuery = IDL.Record({
  'status' : IDL.Opt(ProductStatus),
  'only_approved' : IDL.Bool,
  'max_rental_price' : IDL.Opt(IDL.Nat),
  'only_sanitized' : IDL.Bool,
  'min_rental_price' : IDL.Opt(IDL.Nat),
  'center_id' : IDL.Opt(IDL.Nat),
  'vendor_id' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeReceivingProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveProduct' : IDL.Func([IDL.Nat], [], []),
  'approveUserKyc' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func(
      [IDL.Opt(ProductQuery)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCenter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'registerVendor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProductToCenter' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'uploadProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'center' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'kyc_doc' : IDL.Opt(ExternalBlob),
    'principal' : IDL.Principal,
    'gst_number' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'bank_kyc' : IDL.Opt(IDL.Text),
    'kyc_status' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'kyc_doc' : IDL.Opt(ExternalBlob),
    'gst_number' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'bank_kyc' : IDL.Opt(IDL.Text),
    'kyc_status' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const ProductStatus = IDL.Variant({
    'rented' : IDL.Null,
    'atVendor' : IDL.Null,
    'onTrial' : IDL.Null,
    'underSanitization' : IDL.Null,
    'atCenter' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'deposit_amount' : IDL.Nat,
    'availability_status' : ProductStatus,
    'rental_price' : IDL.Nat,
    'description' : IDL.Text,
    'sanitization_status' : IDL.Bool,
    'approved' : IDL.Bool,
    'center_id' : IDL.Nat,
    'vendor_id' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ProductQuery = IDL.Record({
    'status' : IDL.Opt(ProductStatus),
    'only_approved' : IDL.Bool,
    'max_rental_price' : IDL.Opt(IDL.Nat),
    'only_sanitized' : IDL.Bool,
    'min_rental_price' : IDL.Opt(IDL.Nat),
    'center_id' : IDL.Opt(IDL.Nat),
    'vendor_id' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeReceivingProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveProduct' : IDL.Func([IDL.Nat], [], []),
    'approveUserKyc' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(ProductQuery)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCenter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'registerVendor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProductToCenter' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'uploadProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };