/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'name' : string,
  'deposit_amount' : bigint,
  'availability_status' : ProductStatus,
  'rental_price' : bigint,
  'description' : string,
  'sanitization_status' : boolean,
  'approved' : boolean,
  'center_id' : bigint,
  'vendor_id' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductQuery {
  'status' : [] | [ProductStatus],
  'only_approved' : boolean,
  'max_rental_price' : [] | [bigint],
  'only_sanitized' : boolean,
  'min_rental_price' : [] | [bigint],
  'center_id' : [] | [bigint],
  'vendor_id' : [] | [bigint],
}
export type ProductStatus = { 'rented' : null } |
  { 'atVendor' : null } |
  { 'onTrial' : null } |
  { 'underSanitization' : null } |
  { 'atCenter' : null };
export interface User {
  'id' : bigint,
  'kyc_doc' : [] | [ExternalBlob],
  'principal' : Principal,
  'gst_number' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'bank_kyc' : [] | [string],
  'kyc_status' : boolean,
  'phone' : string,
}
export interface UserProfile {
  'kyc_doc' : [] | [ExternalBlob],
  'gst_number' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'bank_kyc' : [] | [string],
  'kyc_status' : boolean,
  'phone' : string,
}
export type UserRole = { 'center' : null } |
  { 'admin' : null } |
  { 'customer' : null } |
  { 'vendor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeReceivingProduct' : ActorMethod<[bigint, bigint], undefined>,
  'approveProduct' : ActorMethod<[bigint], undefined>,
  'approveUserKyc' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[[] | [ProductQuery]], Array<Product>>,
  'getUser' : ActorMethod<[bigint], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCenter' : ActorMethod<[string, string, string], bigint>,
  'registerCustomer' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'registerVendor' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProductToCenter' : ActorMethod<[bigint, bigint], undefined>,
  'uploadProduct' : ActorMethod<
    [string, string, bigint, bigint, Array<ExternalBlob>],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];